name: Git Tag 

on:
  push:
    branches: [ "main" ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        persist-credentials: false

    - name: Set Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x

    - name: package-version
      run: node -p -e '`PACKAGE_VERSION=${require("./package.json").version}`' >> $GITHUB_ENV

    - name: Run install
      uses: borales/actions-yarn@v4
      with:
        cmd: install # will run `yarn install` command
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # if needed

    - name: Build production bundle
      uses: borales/actions-yarn@v4
      with:
        cmd: build # will run `yarn build` command

    - uses: GuillaumeFalourd/copy-push-files@v1
      with:
        name: lmatas
        target_branch: main
        source_files: dist/ package.json changelog.md
        remote_repository: git@github.com:lareferencia/lrhw.git
        access_token: ${{ secrets.GITHUB_TOKEN }}



